name: release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: helloworld
          tag_name: latest
          files: |
            helloworld
